[+] Added database connection gateway
CSC207-2022F-UofT/course-project-bill-gates pull request #16
Opened 2022-10-27 03:06 UTC by Lei-Tin

2022-10-30 20:27 UTC, Lei-Tin commented
My part of trying to get the Database functioning is pretty much done
The remaining work to be done is just the refacotring of garbage code (Which I accidentally might have included too much :P)

2022-10-30 20:28 UTC, Lei-Tin commented
The way I organized the database is as follows: 
![image](https://user-images.githubusercontent.com/8016180/198900178-ff0e754f-a4ab-4b24-9f1d-e6035084e573.png)

2022-10-31 23:56 UTC, ScottCTD requested changes
Overall GOOD.

2022-10-31 23:56 UTC, ScottCTD commented on src/main/java/billgates/database/MySQLDatabaseGateway.java
> +    private Connection con = null;
naming convention: pls do not use abbreviation where unnecessary

2022-10-31 23:56 UTC, ScottCTD commented on src/main/java/billgates/database/MySQLDatabaseGateway.java
> +                    WHERE date >= CAST('%s' AS DATE) AND date <= CAST('%s' AS DATE)
could u pls use BETWEEN start_date ADN end_date

2022-10-31 23:56 UTC, ScottCTD commented on src/main/java/billgates/database/QueryBillData.java
> +    private final ArrayList<QueryEntryData> entries;
use `List` instead of `ArrayList` as type

2022-10-31 23:56 UTC, ScottCTD commented on src/main/java/billgates/database/MySQLDatabaseGateway.java
> +                int entryId = resultSet.getInt("entry_id");
remove spaghetti pls

2022-10-31 23:56 UTC, ScottCTD commented on src/main/java/billgates/database/MySQLDatabaseGateway.java
> +        ArrayList<QueryEntryData> entries = new ArrayList<>();
change the type to `List`

2022-11-01 00:02 UTC, ScottCTD approved these changes

2022-11-01 00:03 UTC, Lei-Tin commented
> Overall GOOD.

It's ok, you will help me fix this [💩](https://unicode-table.com/en/1F4A9/)

2022-11-02 17:58 UTC, ScottCTD approved these changes
GOOD JOB.

2022-11-02 18:44 UTC, CharlotteChenyy approved these changes

2022-11-06 00:14 UTC, merged